### ISSUE TITLE
Labels with wrong colour codes applied to some versions of component 'clamav*'

### ISSUE THREAD

**Issue by Ricky-Tigg** [repology/repology-wikidata-bot#22]
Hello. [Newest known version](https://www.clamav.net/downloads) of _clamav_, **0.105.0**, whose equivalent in Repology is [clamav*](https://repology.org/projects/c/?search=clamav) , is labelled by that last according to the _devel_ colour code despite no devel version does exist [there](https://github.com/Cisco-Talos/clamav/tags) for that package. Thus that version is intended to be labelled according to the _newest_ colour code, while that colour code is currently applied to its version **0.104.3**. At last and as a consequence, that last mentioned version is intended to be labelled according to the _outdated_ colour code.

**Comment by AMDmi3** [comment]
Let me repeat (repology/repology-updater#1247), the source of problematic status is [wikidata](https://www.wikidata.org/wiki/Q852000). This is not related to this repository at all.

**Comment by Ricky-Tigg** [comment]
That link [_wikidata_](https://www.wikidata.org/wiki/Q852000) is the **very first** in relation to this very subject and here mentioned by you, Thus that cannot make it a repetition. It would have been needed in first place. Now it is there. Though, better late than never.
